# Generated by Django 5.2 on 2025-05-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
