# Generated by Django 5.2 on 2025-05-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewhistorydata',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
