# Generated by Django 5.2 on 2025-05-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_alter_interviewhistorydata_answer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewhistorydata',
            options={'ordering': ['created_at'], 'verbose_name': 'Interview History Data', 'verbose_name_plural': 'Interview History Data'},
        ),
        migrations.RemoveField(
            model_name='interviewhistorydata',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='interviewhistorydata',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='interviewhistorydata',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='interviewhistorydata',
            name='suggestions',
        ),
        migrations.RemoveField(
            model_name='interviewhistorydata',
            name='weaknesses',
        ),
    ]
